spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: <<databasename>>
      username: <<databaseuser>>
      password: <<databasepassword>>      

  jackson:
    default-property-inclusion: NON_NULL
#disabled job run at startup
  batch:
    job:
      enabled: false

# Enable Logging mongo queries
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

employee:
  excel:
    processingfolder: data/processing/
    resultsfolder: data/results/
