spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:batch-sample;MODE=Oracle;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: qaz@123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  data:
    mongodb:
      host: localhost
      port: 27017
      database: spring_batch_excel_mongodb_db
#      username: admin
#      password: pass
      auto-index-creation: true

  jackson:
    default-property-inclusion: NON_NULL
#disabled job run at startup
  batch:
    job:
      enabled: false
      initialize-schema: never
      initializer:
        enabled: false

# Enable Logging mongo queries
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

employee:
  excel:
    processingfolder: data/processing/
    resultsfolder: data/results/
file:
  input: countries.csv
